# Stage 1: Build the application
FROM node:20.19-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY tsconfig*.json ./

# Install dependencies
RUN npm install

# Copy all source files
COPY . .

CMD ["npm", "run", "start:dev"]